# docker-compose up -d
# to check ip use cmd: docker inspect mysql
version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '6033:3306'
    volumes:
      - dbdata:/data/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
      MYSQL_DATABASE: gofibercrudwithmysql
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
    # networks:
    #   mysql:
    #     ipv4_address: 192.168.1.11
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: always
volumes:
  dbdata:
